### PR TITLE
merge from master

### PR DESCRIPTION
**Pull request by Dream-Master**

### CODE REVIEW

**Comment by vovaksenov** [comment]
From what I understand, among other things this would allow getting shadow metal without having a vacuum freezer. Considering the recent warp changes, this could be undesirable.

**Comment by bombcar** [comment]
this doesn't build (easy fixes) but I can't push the fixes to the PR.

Would it be possible for you to PR into a new branch on the GTNH repo so we can test it?

**Comment by Dream-Master** [comment]
no wait . we never add own code to this mid so I will update the repo to the lastest code without this merge. o only want to see how much is changed till the last time

**Review by bombcar — APPROVED** [review]

**Review by bombcar — APPROVED** [review]

**Comment by bombcar** [comment]
I merged the other way around https://github.com/bombcar/Tainted-Magic

Basically pulled our changes by hand; the next step would be to determine what else changed ...

**Comment by bombcar** [comment]
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9048

**Pull request closed without merging**
