### PR TITLE
Fix wand resetting to first day

### PR DESCRIPTION
**Pull request by bombcar**
This implements and fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6868#issuecomment-718237201

Includes a forgegradle update

### CODE REVIEW

**Comment by bombcar** [comment]
wait this is inverted, sets to night lol

**Comment by Dream-Master** [comment]
Let’s better mergelte last version from tainted magic we use 7.6 but 8.1 or 8.2 is out. Was to lazy to compare all this changes and adjust the scripts

**Comment by bombcar** [comment]
This fixes it but - merging the big merge is more :) I'll see what it looks like.

**Comment by Dream-Master** [comment]
oh i see this is version r83  guess we using r76 so the fix will not work because we need to add it to previous version.  I would say we updated to lastest source after the main update and make fixes then

**Comment by bombcar** [comment]
Merging this won’t hurt -  it you need to still use the old 2020 file for next release imo as this already has changed. 

We built the latest code with our changes and they look good but will need some work to integrate with gtnh.

**Comment by Dream-Master** [comment]
the new version have so many files been conflicted that i thought i better delete this repo and for it again

**Comment by bombcar** [comment]
> the new version have so many files been conflicted that i thought i better delete this repo and for it again

if you do that (or force a merge) I have a copy of the GTNH patches (see https://github.com/bombcar/Tainted-Magic) and can reapply them. Only thing missing is the Chinese lang file which I can copy off.

**Comment by Dream-Master** [comment]
yea i will do that good that you saved it. This patches never used because we dont use lastest version. But lets start with it after release

**Comment by bombcar** [comment]
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9048

**Pull request closed without merging**
