### PR TITLE
reduce packet size

### PR DESCRIPTION
**Pull request by Glease**

### CODE REVIEW

**Review by Alastors — APPROVED** [review]
Lmfaoooo love when a pr is significantly larger than it should be because gradle randomly shuffles the imports :kekw:

**Review by chochem — COMMENTED** [review]
we are not actually using the master branch

**Comment by Glease** [comment]
@chochem where are we then? public release from author? That Other Branch in this repo?

**Comment by chochem** [comment]
you want to PR to https://github.com/GTNewHorizons/Tainted-Magic/tree/Tainted-Magic-r7.6

**Pull request closed without merging**
